## CircleCI configuration
version: 2
jobs:
  java8:
    docker:
      - image: circleci/openjdk:8
      
    steps:
      - checkout
      - run: ./gradlew jar
      - run: ./gradlew test
      - store_test_results:
          path: ~/project/build/test-results/test
      - store_artifacts:
          path: ~/project/build/libs/popjava.jar
          
  java9:
    docker:
      - image: circleci/openjdk:9
      
    steps:
      - checkout
      - run: ./gradlew jar
      - run: ./gradlew test
      - store_test_results:
          path: ~/project/build/test-results/test
      - store_artifacts:
          path: ~/project/build/libs/popjava.jar
          
workflows:
  version: 2
  build_8-9:
    jobs:
      - java8
      - java9

