## CircleCI configuration
version: 2
jobs:
  java8:
    docker:
      - image: circleci/openjdk:8
      
    steps:
      - checkout
      - restore_cache:
          keys:
            - pop-cache-{{ checksum "build.gradle" }}
            - pop-cache-
              
      - run: ./gradlew clean build -x test
      - run: ./gradlew test
      - run: sleep 2
      
      - save_cache:
          key: pop-cache-{{ checksum "build.gradle" }}
          when: always
          paths:
            - ~/.gradle
      
      - store_test_results:
          path: ~/project/build/test-results/test
      - store_artifacts:
          path: ~/project/build/popjava.jar
          
  java9:
    docker:
      - image: circleci/openjdk:9
      
    steps:
      - checkout
      - restore_cache:
          keys:
            - pop-cache-{{ checksum "build.gradle" }}
            - pop-cache-
              
      - run: ./gradlew clean build -x test
      - run: ./gradlew test
      - run: sleep 2
      
      - save_cache:
          key: pop-cache-{{ checksum "build.gradle" }}
          when: always
          paths:
            - ~/.gradle
      
      - store_test_results:
          path: ~/project/build/test-results/test
      - store_artifacts:
          path: ~/project/build/popjava.jar
          
workflows:
  version: 2
  build_8-9:
    jobs:
      - java8
      - java9

