## CircleCI configuration
version: 2
jobs:
  java8:
    docker:
      - image: circleci/openjdk:8
      
    steps:
      - checkout
      - run: ant jar-popjava
      - run: ant run-tests
      - store_test_results:
          path: ~/project/build/
      - store_artifacts:
          path: ~/project/build/jar/popjava.jar
          
  java9:
    docker:
      - image: circleci/openjdk:9
      
    steps:
      - checkout
      - run: ant jar-popjava
      - run: ant run-tests
      - store_test_results:
          path: ~/project/build/
      - store_artifacts:
          path: ~/project/build/jar/popjava.jar
          
workflows:
  version: 2
  build_8-9:
    jobs:
      - java8
      - java9

